-- MySQL Script generated by MySQL Workbench
-- Wed Apr 13 16:06:22 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SGV_helpdesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SGV_helpdesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGV_helpdesk` DEFAULT CHARACTER SET utf8 ;
USE `SGV_helpdesk` ;

-- -----------------------------------------------------
-- Table `SGV_helpdesk`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGV_helpdesk`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `password` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `admin_type` INT NULL DEFAULT NULL COMMENT '',
  `created_time` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `updated_time` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `iduser_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SGV_helpdesk`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGV_helpdesk`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cbs_lastname` VARCHAR(45) NOT NULL COMMENT '',
  `cbs_firstname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `admins_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idemployee_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_employee_admins1_idx` (`admins_id` ASC)  COMMENT '',
  CONSTRAINT `fk_employee_admins1`
    FOREIGN KEY (`admins_id`)
    REFERENCES `SGV_helpdesk`.`admins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SGV_helpdesk`.`problem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGV_helpdesk`.`problem` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `problem_type` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idproblem_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SGV_helpdesk`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGV_helpdesk`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `category_type` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGV_helpdesk`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGV_helpdesk`.`record` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `employee_name` VARCHAR(45) NOT NULL COMMENT '',
  `action_taken` VARCHAR(255) NOT NULL COMMENT '',
  `date_recieved` DATETIME NULL DEFAULT NULL COMMENT '',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `employee_id` INT NOT NULL COMMENT '',
  `short_description` VARCHAR(255) NOT NULL COMMENT '',
  `problem_id` INT NOT NULL COMMENT '',
  `category_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_record_employee1_idx` (`employee_id` ASC)  COMMENT '',
  INDEX `fk_record_problem1_idx` (`problem_id` ASC)  COMMENT '',
  INDEX `fk_record_category1_idx` (`category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_record_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `SGV_helpdesk`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_problem1`
    FOREIGN KEY (`problem_id`)
    REFERENCES `SGV_helpdesk`.`problem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `SGV_helpdesk`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `SGV_helpdesk`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGV_helpdesk`.`reports` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tnf` INT NULL DEFAULT NULL COMMENT '',
  `lan_cable` INT NULL DEFAULT NULL COMMENT '',
  `ip_phone` INT NULL DEFAULT NULL COMMENT '',
  `remarks` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `problem_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idreports_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_reports_problem1_idx` (`problem_id` ASC)  COMMENT '',
  CONSTRAINT `fk_reports_problem1`
    FOREIGN KEY (`problem_id`)
    REFERENCES `SGV_helpdesk`.`problem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
